kind: Deployment
apiVersion: apps/v1
metadata:
  name: dops-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dops-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dops-ui
      annotations:
        timestamp: '1633042690'
    spec:
      containers:
        - name: dops-ui-container
          image: 2204198622/elg-ksi:ui-production-it-1.8.47 
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: dops-acr
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
