- hosts: master
  become: true
  become_user: ubuntu
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: true
  become_user: root
  tasks:
    - name: clearing config /etc/containerd/config.toml
      ignore_errors: yes
      file:
        state: absent
        path: /etc/containerd/config.toml
        
    - name: run conteiners
      shell:
         "systemctl restart containerd"

    - name: get join command
      shell: 
         "{{ hostvars['master'].join_command }} >> /tmp/node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
