- hosts: masters
  become: true
  become_user: root
  tasks:
    - name: create directory for stdout
      become: yes
      become_user: root
      file:
        path: /DATA/K8S/stdout_creat_cluster
        state: directory
        mode: 0777
        #      when: p.stat.exists is defined and not p.stat.exists

#    - name: Initialize the Kubernetes cluster using kubeadm
#      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
#    - name: create file
#      file:
#        path: /DATA/K8S/stdout_creat_cluster/pod_network_setup.txt
#        state: touch
#        owner: ubuntu
#        mode: 0777
#      when: p.stat.exists is defined and not p.stat.exists

    - name: initialize the cluster
      shell: 
         "kubeadm init --pod-network-cidr=10.244.0.0/16 >> /DATA/K8S/stdout_creat_cluster/cluster_initialized.txt"

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: 
         "kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> /DATA/K8S/stdout_creat_cluster/pod_network_setup.txt"
